LPD-18884 add functional tests for scriptElementsAttributes in globalJS client extension
liferay-platform-experience/liferay-portal pull request #561
Opened 2024-04-22 17:59 UTC by thiago-buarqque

2024-04-22 17:59 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-04-22 20:17 UTC, thiago-buarqque commented
ci:test:playwright

2024-04-22 20:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/9628/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9628/jenkins-report.html">here</a>.</b></p>

2024-04-22 22:04 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 21 out of 28 jobs passed in 1 hour 47 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/501">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1297401_9628</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d56089f945aa90d7960108eba7f17186ac74963c">d56089f945aa90d7960108eba7f17186ac74963c</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/92e97c58318db1faa133bb4bfa79603244a66c92">92e97c58318db1faa133bb4bfa79603244a66c92</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2562234631">EE Development Acceptance (master) - 500 - 2024-04-19[12:38:21]</a></p><details><summary><strong>ci:test:playwright - 21 out of 28 jobs PASSED</strong></summary><div><h4>7 Failed Jobs:</h4><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/9628/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-compile-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1087834/">playwright-compile-jdk8/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/900845/">playwright-js-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1084860/">playwright-js-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/984897/"><strike>playwright-js-tomcat90-mysql57-jdk8/2/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/968620/">playwright-js-tomcat90-mysql57-jdk8/3/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1087836/">playwright-js-tomcat90-mysql57-jdk8/4/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/576942/">playwright-js-tomcat90-mysql57-jdk8/5/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/617708/"><strike>playwright-js-tomcat90-mysql57-jdk8/6/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/968619/">playwright-js-tomcat90-mysql57-jdk8/7/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880073/">playwright-js-tomcat90-mysql57-jdk8/8/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/617707/">playwright-js-tomcat90-mysql57-jdk8/9/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/807745/"><strike>playwright-js-tomcat90-mysql57-jdk8/10/0</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880075/">playwright-js-tomcat90-mysql57-jdk8/11/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/968621/">playwright-js-tomcat90-mysql57-jdk8/12/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1087838/">playwright-js-tomcat90-mysql57-jdk8/13/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/923241/">playwright-js-tomcat90-mysql57-jdk8/14/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/617709/">playwright-js-tomcat90-mysql57-jdk8/15/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/939129/">playwright-js-tomcat90-mysql57-jdk8/16/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/900846/"><strike>playwright-js-tomcat90-mysql57-jdk8/17/0</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880072/"><strike>playwright-js-tomcat90-mysql57-jdk8/18/0</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1087833/">playwright-js-tomcat90-mysql57-jdk8/19/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1087835/"><strike>playwright-js-tomcat90-mysql57-jdk8/20/0</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1084859/">playwright-js-tomcat90-mysql57-jdk8/21/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/900844/">playwright-js-tomcat90-mysql57-jdk8/22/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880074/">playwright-js-tomcat90-mysql57-jdk8/23/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/807746/">playwright-js-tomcat90-mysql57-jdk8/24/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/939128/">playwright-js-tomcat90-mysql57-jdk8/25/0</a></li></ul></li></ul></div><details><summary><strong>21 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9628/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880072//consoleText">playwright-js-tomcat90-mysql57-jdk8/18/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-04/test-1-29/test-portal-acceptance-pullrequest(master)/9628/playwright-js-tomcat90-mysql57-jdk8/18/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880072/testReport/headless-builder-web_post.spec/ts">headless-builder-web/post.spec.ts</a></summary><div><ol><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880072//testReport/headless-builder-web_post.spec/ts/can_create_post_endpoint_with_different_request_and_response_schema">can create post endpoint with different request and response schema</a></li></ol></div></details></li></ol></div></li></ol><hr/><details><summary><strong>Failures in common with <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at 92e97c58318db1faa133bb4bfa79603244a66c92:</strong></summary><ol><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/984897//consoleText">playwright-js-tomcat90-mysql57-jdk8/2/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-04/test-1-29/test-portal-acceptance-pullrequest(master)/9628/playwright-js-tomcat90-mysql57-jdk8/2/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-32.liferay.com/job/test-portal-a [...]

2024-04-22 22:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/9628/">test-portal-acceptance-pullrequest(master)#9628</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9628/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-platform-experience/liferay-portal/pull/561">liferay-platform-experience#561</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2562596753">[master] ci:test:playwright - thiago-buarqque &gt; liferay-platform-experience - PR#561 - 2024-04-22[13:17:29]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2562596753<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/21335/">publish-testray-report#21335</a><br/></div></div>

2024-04-23 07:25 UTC, ethib137 requested changes
Looking good... just a few changes.

2024-04-23 14:56 UTC, thiago-buarqque commented on modules/test/playwright/tests/client-extension-web/js.spec.ts
> +		.locator('xpath=../td/select');
Done, changed to
```
const loadTypeSelector = page
		.locator(`tr`, {hasText: clientExtensionName})
		.locator(".load-type-select");
```

2024-04-23 17:30 UTC, thiago-buarqque commented
ci:test:sf

2024-04-23 17:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/8515/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/8515/jenkins-report.html">here</a>.</b></p>

2024-04-23 17:32 UTC, thiago-buarqque commented
ci:test:playwright

2024-04-23 17:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4226/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4226/jenkins-report.html">here</a>.</b></p>

2024-04-23 17:34 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d56089f945aa90d7960108eba7f17186ac74963c">d56089f945aa90d7960108eba7f17186ac74963c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thiago-buarqque/liferay-portal/tree/LPD-18884">LPD-18884</a><br/>Branch GIT ID: <a href="https://github.com/thiago-buarqque/liferay-portal/commit/cf5f7c74f2588dff678350c2f4c1f7ef8a7c98b2">cf5f7c74f2588dff678350c2f4c1f7ef8a7c98b2</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/8515/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/8515/jenkins-report.html">here</a>.</h5></details></html>

2024-04-23 17:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/8515/">test-portal-source-format#8515</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/8515/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-platform-experience/liferay-portal/pull/561">liferay-platform-experience#561</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2562872106">[master] ci:test:sf - thiago-buarqque &gt; liferay-platform-experience - PR#561 - 2024-04-23[10:30:27]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2562872106<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/32140/">publish-testray-report#32140</a><br/></div></div>

2024-04-23 19:23 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 20 out of 28 jobs passed in 1 hour 51 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d56089f945aa90d7960108eba7f17186ac74963c">d56089f945aa90d7960108eba7f17186ac74963c</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d56089f945aa90d7960108eba7f17186ac74963c">d56089f945aa90d7960108eba7f17186ac74963c</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2562627015">EE Development Acceptance (master) - 501 - 2024-04-22[12:38:53]</a></p><details><summary><strong>ci:test:playwright - 20 out of 28 jobs PASSED</strong></summary><div><h4>8 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4226/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-compile-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995806/">playwright-compile-jdk8/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995813/">playwright-js-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995814/">playwright-js-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880947/"><strike>playwright-js-tomcat90-mysql57-jdk8/2/0</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995812/">playwright-js-tomcat90-mysql57-jdk8/3/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880944/">playwright-js-tomcat90-mysql57-jdk8/4/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880946/">playwright-js-tomcat90-mysql57-jdk8/5/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880945/"><strike>playwright-js-tomcat90-mysql57-jdk8/6/0</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995808/"><strike>playwright-js-tomcat90-mysql57-jdk8/7/0</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995807/">playwright-js-tomcat90-mysql57-jdk8/8/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880940/">playwright-js-tomcat90-mysql57-jdk8/9/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/901718/"><strike>playwright-js-tomcat90-mysql57-jdk8/10/0</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/618652/">playwright-js-tomcat90-mysql57-jdk8/11/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/618653/">playwright-js-tomcat90-mysql57-jdk8/12/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880948/">playwright-js-tomcat90-mysql57-jdk8/13/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/577785/"><strike>playwright-js-tomcat90-mysql57-jdk8/14/0</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995815/">playwright-js-tomcat90-mysql57-jdk8/15/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880949/">playwright-js-tomcat90-mysql57-jdk8/16/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/901719/"><strike>playwright-js-tomcat90-mysql57-jdk8/17/0</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995805/">playwright-js-tomcat90-mysql57-jdk8/18/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995804/">playwright-js-tomcat90-mysql57-jdk8/19/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995809/"><strike>playwright-js-tomcat90-mysql57-jdk8/20/0</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880942/">playwright-js-tomcat90-mysql57-jdk8/21/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880941/">playwright-js-tomcat90-mysql57-jdk8/22/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880943/">playwright-js-tomcat90-mysql57-jdk8/23/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995810/">playwright-js-tomcat90-mysql57-jdk8/24/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995811/">playwright-js-tomcat90-mysql57-jdk8/25/0</a></li></ul></li></ul></div><details><summary><strong>20 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4226/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995808//consoleText">playwright-js-tomcat90-mysql57-jdk8/7/0</a><ol><li><details><summary><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995808/testReport/com.liferay.jenkins/JenkinsLogAsserterTest">com.liferay.jenkins.JenkinsLogAsserterTest</a></summary><div><ol><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995808//testReport/com.liferay.jenkins/JenkinsLogAsserterTest/testScanJenkinsLog">testScanJenkinsLog</a></li></ol></div></details></li></ol></div></li><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/577785//consoleText">playwright-js-tomcat90-mysql57-jdk8/14/0</a></div></li></ol><hr/><details><summary><strong>Failures in common with <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at d56089f945aa90d7960108eba7f17186ac74963c:</strong></summary><ol><li><div><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880947//consoleText">playwright-js-tomcat90-mysql57-jdk8/2/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-04/test-1-32/test-portal-acceptance-pullrequest(master)/4226/playwright-js-tomcat90-mysql57-jdk8/2/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880947/testReport/commerce_commerceSpecificationFragment.spec/ts">commerce/commerceSpecificationFragment.spec.ts</a></summary><div><ol><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880947//testReport/commerce_commerceSpecificationFragment.spec/ts/Product_specification_fragment_only_shows_correct_specifications">Product specification fragment only shows correct specifications</a></li></ol></div></details></li><li><details><summary><a href="https:/ [...]

2024-04-23 19:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4226/">test-portal-acceptance-pullrequest(master)#4226</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4226/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-platform-experience/liferay-portal/pull/561">liferay-platform-experience#561</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2562911146">[master] ci:test:playwright - thiago-buarqque &gt; liferay-platform-experience - PR#561 - 2024-04-23[10:32:32]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2562911146<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/32143/">publish-testray-report#32143</a><br/></div></div>

2024-04-24 10:49 UTC, thiago-buarqque commented
Hey @ethib137, the playwright errors are unrelated. If my changes are fine, please forward to Brian

2024-04-24 12:51 UTC, ethib137 requested changes
Just a couple minor changes. Thanks Thiago!

2024-04-24 12:51 UTC, ethib137 commented on modules/test/playwright/tests/client-extension-web/js.spec.ts
> +		.locator(`tr`, {hasText: clientExtensionName})
The `tr` should be wrapped with normal single quotes.

2024-04-24 12:51 UTC, ethib137 commented on modules/test/playwright/tests/client-extension-web/js.spec.ts
> +type TGlobalJSWithAttributesTest = {
This should match the method name: `TGlobalJSClientExtensionWithAttributes`

2024-04-24 13:54 UTC, thiago-buarqque commented
ci:test:playwright

2024-04-24 13:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/11693/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11693/jenkins-report.html">here</a>.</b></p>

2024-04-24 15:41 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 22 out of 28 jobs passed in 1 hour 43 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/504">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1277401_11693</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c808538beb5fcf685c8696719a287cc7c33b8af4">c808538beb5fcf685c8696719a287cc7c33b8af4</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7f5f1101d86b73e79f060f5fc21e0fd09ee8fe94">7f5f1101d86b73e79f060f5fc21e0fd09ee8fe94</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2563150206">EE Development Acceptance (master) - 503 - 2024-04-23[16:38:09]</a></p><details><summary><strong>ci:test:playwright - 22 out of 28 jobs PASSED</strong></summary><div><h4>6 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/11693/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-compile-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/902470/">playwright-compile-jdk8/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/986444/">playwright-js-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/619499/">playwright-js-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/902472/"><strike>playwright-js-tomcat90-mysql57-jdk8/2/0</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/809494/">playwright-js-tomcat90-mysql57-jdk8/3/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1086927/">playwright-js-tomcat90-mysql57-jdk8/4/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/970296/">playwright-js-tomcat90-mysql57-jdk8/5/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/863047/"><strike>playwright-js-tomcat90-mysql57-jdk8/6/0</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/925040/">playwright-js-tomcat90-mysql57-jdk8/7/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/619497/">playwright-js-tomcat90-mysql57-jdk8/8/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/863046/">playwright-js-tomcat90-mysql57-jdk8/9/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/925042/">playwright-js-tomcat90-mysql57-jdk8/10/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1086928/">playwright-js-tomcat90-mysql57-jdk8/11/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/809495/">playwright-js-tomcat90-mysql57-jdk8/12/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/863048/"><strike>playwright-js-tomcat90-mysql57-jdk8/13/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/970297/">playwright-js-tomcat90-mysql57-jdk8/14/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/970298/">playwright-js-tomcat90-mysql57-jdk8/15/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/986445/">playwright-js-tomcat90-mysql57-jdk8/16/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/619500/"><strike>playwright-js-tomcat90-mysql57-jdk8/17/0</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/986442/">playwright-js-tomcat90-mysql57-jdk8/18/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/986441/">playwright-js-tomcat90-mysql57-jdk8/19/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1086941/">playwright-js-tomcat90-mysql57-jdk8/20/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/986443/">playwright-js-tomcat90-mysql57-jdk8/21/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/970295/">playwright-js-tomcat90-mysql57-jdk8/22/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/619498/">playwright-js-tomcat90-mysql57-jdk8/23/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/902471/"><strike>playwright-js-tomcat90-mysql57-jdk8/24/0</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/925041/">playwright-js-tomcat90-mysql57-jdk8/25/0</a></li></ul></li></ul></div><details><summary><strong>22 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11693/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/902472//consoleText">playwright-js-tomcat90-mysql57-jdk8/2/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-04/test-1-27/test-portal-acceptance-pullrequest(master)/11693/playwright-js-tomcat90-mysql57-jdk8/2/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/902472/testReport/commerce_commerce-order-content-web_pendingOrder.spec/ts">commerce/commerce-order-content-web/pendingOrder.spec.ts</a></summary><div><ol><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/902472//testReport/commerce_commerce-order-content-web_pendingOrder.spec/ts/Edit_pending_order_item_with_UOM">Edit pending order item with UOM</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/902472//testReport/commerce_commerce-order-content-web_pendingOrder.spec/ts/LPD_4174_Sales_agent_can_recieve_email_notifications_for_new_orders_placed_to_their_accounts">LPD-4174 Sales agent can recieve email notifications for new orders placed to their accounts</a></li></ol></div></details></li></ol></div></li><li><div><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/863048//consoleText">playwright-js-tomcat90-mysql57-jdk8/13/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-04/test-1-27/test-portal-acceptance-pullrequest(master)/11693/playwright-js-tomcat90-mysql57-jdk8/13/0/playwright-report/index.h [...]

2024-04-24 17:18 UTC, ethib137 commented
ci:forward

2024-04-24 17:18 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-04-24 17:18 UTC, ethib137 approved these changes
LGTM

2024-04-24 17:20 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/3232/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3232/jenkins-report.html">here</a>.</b></p>

2024-04-24 17:23 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/da60142e913972b68308b5c3623c7c5bd99a1c6b">da60142e913972b68308b5c3623c7c5bd99a1c6b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thiago-buarqque/liferay-portal/tree/LPD-18884">LPD-18884</a><br/>Branch GIT ID: <a href="https://github.com/thiago-buarqque/liferay-portal/commit/120c0a02b165af78ce6b288577728ed923f2bad0">120c0a02b165af78ce6b288577728ed923f2bad0</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/3232/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3232/jenkins-report.html">here</a>.</h5></details></html>

2024-04-24 17:24 UTC, closed without merging

2024-04-24 17:24 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/149627
[Console](https://test-1-36.liferay.com/job/test-portal-source-format/3232//consoleFull)

2024-04-24 17:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/3232/">test-portal-source-format#3232</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3232/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-platform-experience/liferay-portal/pull/561">liferay-platform-experience#561</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2563357712">[master] ci:test:sf - thiago-buarqque &gt; liferay-platform-experience - PR#561 - 2024-04-24[10:18:37]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2563357712<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/12966/">publish-testray-report#12966</a><br/></div></div>

2024-04-24 17:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/9365/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9365/jenkins-report.html">here</a>.</b></p>

2024-04-24 17:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/9365/">test-portal-acceptance-pullrequest(master)#9365</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9365/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-platform-experience/liferay-portal/pull/561">liferay-platform-experience#561</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2563357950">[master] ci:test:relevant - thiago-buarqque &gt; liferay-platform-experience - PR#561 - 2024-04-24[10:35:07]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2563357950<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/19508/">publish-testray-report#19508</a><br/></div></div>