LPD-33047 Allow style books to be applied to a page based on the frontend token definition applied to the page
liferay-platform-experience/liferay-portal pull request #796
Opened 2024-11-19 14:21 UTC by algobob

2024-11-19 14:21 UTC, liferay-continuous-integration commented
The following guidelines have been set by the owner of this repository: 
- &nbsp;&nbsp;&nbsp;&nbsp;"Thank you for sending this PR to liferay-platform-experience. If you haven't already,take this opportunity to review our [pull request guidelines](https://liferay.atlassian.net/wiki/spaces/PEDS/pages/2915598365). For additional help,please reach out via the [appropriate channels](https://liferay.atlassian.net/wiki/spaces/PEDS/overview#%3Aslack%3A-Slack-Channels)."

2024-11-19 14:21 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-11-19 17:44 UTC, algobob commented
ci:test:sf

2024-11-19 17:46 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/7001/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/7001/jenkins-report.html">here</a>.</b></p>

2024-11-19 17:49 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e2347c3f89b418c60417c0e2139591b27c420f69">e2347c3f89b418c60417c0e2139591b27c420f69</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/algobob/liferay-portal/tree/LPD-33047-2">LPD-33047-2</a><br/>Branch GIT ID: <a href="https://github.com/algobob/liferay-portal/commit/df6280469223a9e3412d073d529423ec0bb72158">df6280469223a9e3412d073d529423ec0bb72158</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/7001/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/7001/jenkins-report.html">here</a>.</h5></details></html>

2024-11-19 17:54 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/7001/">test-portal-source-format#7001</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/7001/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-platform-experience/liferay-portal/pull/796">liferay-platform-experience#796</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/72258287">[master] ci:test:sf - algobob &gt; liferay-platform-experience - PR#796 - 2024-11-19[09:45:09]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>72258287<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/25570/">publish-testray-report#25570</a><br/></div></div>

2024-11-26 14:00 UTC, thiago-buarqque approved these changes
Looks good to me.

@algobob  I'd just merge the breaking changes commits.
1. [LPD-33047 Fetch frontend token definition based on company id, layout id and theme id](https://github.com/liferay-platform-experience/liferay-portal/pull/796/commits/fce1014a5ebfbb724d500ebcd5604d2a1de5a104)
2. [LPD-33047 Remove old theme matching validation](https://github.com/liferay-platform-experience/liferay-portal/pull/796/commits/a76923eaf4e40429420db11ec9e80b6494d24796)

It's good to put the breaking change message together with the breaking code, so it's easier to find the changes in the future.

I did not give much attention to the frontend side, I am mostly handling SF here, since I am out of context.

2024-11-27 18:03 UTC, algobob commented
> Looks good to me.
> 
> @algobob I'd just merge the breaking changes commits.
> 
> 1. [LPD-33047 Fetch frontend token definition based on company id, layout id and theme id](https://github.com/liferay-platform-experience/liferay-portal/pull/796/commits/fce1014a5ebfbb724d500ebcd5604d2a1de5a104)
> 2. [LPD-33047 Remove old theme matching validation](https://github.com/liferay-platform-experience/liferay-portal/pull/796/commits/a76923eaf4e40429420db11ec9e80b6494d24796)
> 
> It's good to put the breaking change message together with the breaking code, so it's easier to find the changes in the future.
> 
> I did not give much attention to the frontend side, I am mostly handling SF here, since I am out of context.

cool, it makes sense for me too. Lets just decide a pattern with Evan. I see many ways of using: "baseline", "semantic version" and same commit as you mentioned. What do you think? cc: @ethib137

2024-11-28 14:01 UTC, algobob commented
> > cool, it makes sense for me too. Lets just decide a pattern with Evan. I see many ways of using: "baseline", "semantic version" and same commit as you mentioned. What do you think? cc: @ethib137
> 
> I don't think I understand exactly what the question is. Could you explain a bit more @algobob

Sure. So, we need to add that "breaking change" message template when we're implementing changes that affect `*-api` modules interface. i.e: update params, add new methods...  Some people just add the message in a commit with the new versions like this [one](https://github.com/liferay/liferay-portal/commit/44648ff0b15fe5936f835b5ae5d7570903dab3a3) and other people add the message into the commit with the java code changes, like this [one](https://github.com/liferay/liferay-portal/commit/49b6c1496e13180a173a99a3c9e29b62462e02f8)

Then my question is about which way should we follow?

2024-11-29 05:42 UTC, ethib137 commented
> > > cool, it makes sense for me too. Lets just decide a pattern with Evan. I see many ways of using: "baseline", "semantic version" and same commit as you mentioned. What do you think? cc: @ethib137
> > 
> > 
> > I don't think I understand exactly what the question is. Could you explain a bit more @algobob
> 
> Sure. So, we need to add that "breaking change" message template when we're implementing changes that affect `*-api` modules interface. i.e: update params, add new methods... Some people just add the message in a commit with the new versions only like this [one](https://github.com/liferay/liferay-portal/commit/44648ff0b15fe5936f835b5ae5d7570903dab3a3) and other people add the message into the commit with the java code changes, like this [one](https://github.com/liferay/liferay-portal/commit/49b6c1496e13180a173a99a3c9e29b62462e02f8)
> 
> Then my question is about which way should we follow?

According to our [documentation](https://liferay.atlassian.net/wiki/spaces/ENGR/pages/2489483265/Process+to+register+breaking+changes+in+commits) on this, the breaking change commit should be the commit where the breaking change occurs in the java code.

2024-11-29 17:33 UTC, algobob commented
ci:test:sf

2024-11-29 17:52 UTC, algobob commented
> According to our [documentation](https://liferay.atlassian.net/wiki/spaces/ENGR/pages/2489483265/Process+to+register+breaking+changes+in+commits) on this, the breaking change commit should be the commit where the breaking change occurs in the java code.

Cool. Done :heavy_check_mark:

2024-12-02 15:50 UTC, ealonso commented
Hey @algobob,

A couple of things since this pr should be reviewed by @liferay-page-management team.

1. You need to add the buildLang commit
2. If the new language key is a sentence it should ends in a "."
3. Please execute source format task after every commit, if not it is really difficult to review your changes, It is not make sense to split your code in commits if you mixed logic between commits and you don't have formatted every commit properly.
4. Please do not create unnecessary components, StyleBookManager, shouldn't be a component, also as I can see it is only used in ContentPageEditorDisplayContext, so it is better if you move all the logic to this class.

Regards,
Eudaldo.

2024-12-02 17:51 UTC, algobob commented
> Hey @algobob,
> 
> A couple of things since this pr should be reviewed by @liferay-page-management team.
> 
> 1. You need to add the buildLang commit
> 2. If the new language key is a sentence it should ends in a "."
> 3. Please execute source format task after every commit, if not it is really difficult to review your changes, It is not make sense to split your code in commits if you mixed logic between commits and you don't have formatted every commit properly.
> 4. Please do not create unnecessary components, StyleBookManager, shouldn't be a component, also as I can see it is only used in ContentPageEditorDisplayContext, so it is better if you move all the logic to this class.
> 
> Regards, Eudaldo.

@ealonso 

1.  It seems its not a practice in our team anymore. Also, Brian run it before merging
2.  good catch. updating...
3.  cool. updating...
4.  oh, my idea was to make easier to unit test this new behavior by isolating, instead of make `ContentPageEditorDisplayContext`  even bigger than already is and test it via integration test only.  The `manager` package initially seems to be a good place. Some methods of these managers also are used in one place only i.e: `ContentManager#getFragmentEntryLinkMappedLayoutDisplayPageObjectProviders `, `FormItemManager#addFormStepLayoutStructureItems`, `FragmentCollectionManager#updateSortedFragmentCollectionKeys` ...

  Should I move it to `ContentPageEditorDisplayContext` anyway?

2024-12-10 18:39 UTC, algobob commented
ci:test:sf

2024-12-10 18:40 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/6981/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6981/jenkins-report.html">here</a>.</b></p>

2024-12-10 18:43 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c">c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/algobob/liferay-portal/tree/LPD-33047-2">LPD-33047-2</a><br/>Branch GIT ID: <a href="https://github.com/algobob/liferay-portal/commit/07933dece541b3a207bd28544cc642c3be523e43">07933dece541b3a207bd28544cc642c3be523e43</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6981/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6981/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: Incorrect commit message: Missing breaking change in commit messages when the major version bumps up: ./modules/apps/frontend-token/frontend-token-definition-api/bnd.bnd (SourceCheck:BNDBreakingChangeCommitMessageCheck)
     [java] 2: Do not use org.jsoup, see LPD-42623: ./modules/apps/layout/layout-content-page-editor-web/src/main/java/com/liferay/layout/content/page/editor/web/internal/display/context/ContentPageEditorDisplayContext.java (SourceCheck:IllegalImportsCheck)
     [java] 3: ./modules/apps/layout/layout-content-page-editor-web/src/test/java/com/liferay/layout/content/page/editor/web/internal/display/context/ContentPageEditorDisplayContextTest.java expected:&lt;...opyrightText: (c) 20[24] Liferay, Inc. https...&gt; but was:&lt;...opyrightText: (c) 20[00] Liferay, Inc. https...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:472)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:301)
[stopwatch] [run.batch.test.action: 1:49.309 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1382015209.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1569528400
[junitreport] Loading stylesheet ile:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 157ms
[junitreport] Deleting: /tmp/null1569528400
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results</pre></details></html>

2024-12-10 18:45 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6981/">test-portal-source-format#6981</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6981/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-platform-experience/liferay-portal/pull/796">liferay-platform-experience#796</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/88661018">[master] ci:test:sf - algobob &gt; liferay-platform-experience - PR#796 - 2024-12-10[10:39:33]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>88661018<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/26598/">publish-testray-report#26598</a><br/></div></div>

2024-12-10 20:54 UTC, algobob commented
ci:test:sf

2024-12-10 20:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/3824/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3824/jenkins-report.html">here</a>.</b></p>

2024-12-10 20:59 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c3244865c1a89947fb723b24875ae56cddb15d15">c3244865c1a89947fb723b24875ae56cddb15d15</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/algobob/liferay-portal/tree/LPD-33047-2">LPD-33047-2</a><br/>Branch GIT ID: <a href="https://github.com/algobob/liferay-portal/commit/29b169a631a498314bbafeb25147e8fbb93cd350">29b169a631a498314bbafeb25147e8fbb93cd350</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/3824/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3824/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Do not use org.jsoup, see LPD-42623: ./modules/apps/layout/layout-content-page-editor-web/src/main/java/com/liferay/layout/content/page/editor/web/internal/display/context/ContentPageEditorDisplayContext.java (SourceCheck:IllegalImportsCheck)
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:472)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:301)
[stopwatch] [run.batch.test.action: 2:01.734 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null636472495.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null652560735
[junitreport] Loading stylesheet ile:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 157ms
[junitreport] Deleting: /tmp/null652560735
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 12-10-2024 12:59:10:885 PST
[stopwatch] [run.batch.test.tear.down: 0.000 sec]
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null636472495.properties

print-gc-logs:
     [echo] </pre></details></html>

2024-12-10 21:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/3824/">test-portal-source-format#3824</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3824/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-platform-experience/liferay-portal/pull/796">liferay-platform-experience#796</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/88710991">[master] ci:test:sf - algobob &gt; liferay-platform-experience - PR#796 - 2024-12-10[12:55:12]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>88710991<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/15632/">publish-testray-report#15632</a><br/></div></div>

2024-12-10 21:38 UTC, algobob commented
ci:test:sf

2024-12-10 21:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/6987/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6987/jenkins-report.html">here</a>.</b></p>

2024-12-10 21:45 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/901ac2b7c615e7cc30aefe18c834b587195e506c">901ac2b7c615e7cc30aefe18c834b587195e506c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/algobob/liferay-portal/tree/LPD-33047-2">LPD-33047-2</a><br/>Branch GIT ID: <a href="https://github.com/algobob/liferay-portal/commit/29b169a631a498314bbafeb25147e8fbb93cd350">29b169a631a498314bbafeb25147e8fbb93cd350</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6987/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6987/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Do not use org.jsoup, see LPD-42623: ./modules/apps/layout/layout-content-page-editor-web/src/main/java/com/liferay/layout/content/page/editor/web/internal/display/context/ContentPageEditorDisplayContext.java (SourceCheck:IllegalImportsCheck)
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:472)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:301)
[stopwatch] [run.batch.test.action: 2:24.755 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1510726799.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null49671197
[junitreport] Loading stylesheet ile:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 170ms
[junitreport] Deleting: /tmp/null49671197
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 12-10-2024 13:44:49:381 PST
[stopwatch] [run.batch.test.tear.down: 0.000 sec]
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1510726799.properties

print-gc-logs:
     [echo] </pre></details></html>

2024-12-10 21:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6987/">test-portal-source-format#6987</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6987/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-platform-experience/liferay-portal/pull/796">liferay-platform-experience#796</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/88721070">[master] ci:test:sf - algobob &gt; liferay-platform-experience - PR#796 - 2024-12-10[13:40:10]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>88721070<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/26609/">publish-testray-report#26609</a><br/></div></div>

2024-12-11 16:29 UTC, thiago-buarqque requested changes
Thanks @algobob, just a few comments, let me know if you disagree with any of them

2024-12-11 16:29 UTC, thiago-buarqque commented on modules/apps/layout/layout-content-page-editor-web/src/test/java/com/liferay/layout/content/page/editor/web/internal/display/context/ContentPageEditorDisplayContextTest.java
> +			));
Create a variable for 

```java
result.get(
    0
)
```

2024-12-11 16:29 UTC, thiago-buarqque commented on modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties
> +only-style-books-based-on-the-frontend-token-definition-provided-by-x-theme-are-visible=Only style books based on the frontend token definition provided by {0} theme are visible
We probably have a period at the end of the sentence in the design. You should add it here as well

2024-12-11 16:29 UTC, thiago-buarqque commented on modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/page_design_options/components/PageDesignOptionsSidebar.js
Frontend side looks fine to me, but better to have a stronger opinion from @pat270

2024-12-11 16:29 UTC, thiago-buarqque commented on modules/apps/layout/layout-content-page-editor-web/src/main/java/com/liferay/layout/content/page/editor/web/internal/display/context/ContentPageEditorDisplayContext.java
>  					Layout layout = themeDisplay.getLayout();
Other methods in this that fill the attributes in this `HashMapBuilder` use `Layout`, `Theme` and other info from the themeDisplay to build their values.

2024-12-11 16:58 UTC, algobob commented
ci:test:sf

2024-12-11 17:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/7146/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/7146/jenkins-report.html">here</a>.</b></p>

2024-12-11 17:04 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7500a1d19d00706e027f3a924643af94b4caa2c5">7500a1d19d00706e027f3a924643af94b4caa2c5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/algobob/liferay-portal/tree/LPD-33047-2">LPD-33047-2</a><br/>Branch GIT ID: <a href="https://github.com/algobob/liferay-portal/commit/344857e9ffa9b900ce3b34ba86b5e2b2c1bd46b1">344857e9ffa9b900ce3b34ba86b5e2b2c1bd46b1</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/7146/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/7146/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Do not use org.jsoup, see LPD-42623: ./modules/apps/layout/layout-content-page-editor-web/src/main/java/com/liferay/layout/content/page/editor/web/internal/display/context/ContentPageEditorDisplayContext.java (SourceCheck:IllegalImportsCheck)
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:472)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:301)
[stopwatch] [run.batch.test.action: 1:54.851 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1389395935.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null820285745
[junitreport] Loading stylesheet ile:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 143ms
[junitreport] Deleting: /tmp/null820285745
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 12-11-2024 09:03:36:073 PST
[stopwatch] [run.batch.test.tear.down: 0.001 sec]
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1389395935.properties

print-gc-logs:
     [echo] </pre></details></html>

2024-12-11 17:08 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/7146/">test-portal-source-format#7146</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/7146/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-platform-experience/liferay-portal/pull/796">liferay-platform-experience#796</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/89445393">[master] ci:test:sf - algobob &gt; liferay-platform-experience - PR#796 - 2024-12-11[08:58:16]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>89445393<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/26048/">publish-testray-report#26048</a><br/></div></div>

2024-12-11 17:11 UTC, thiago-buarqque approved these changes
LGTM. @algobob  please move forward with this one asking for the other team's review

2024-12-11 17:12 UTC, algobob commented
> ### ❌ ci:test:sf - 0 out of 1 jobs passed in 6 minutes
> Click here for more details.
> #### Base Branch:
> Branch Name: [master](https://github.com/liferay/liferay-portal/tree/master)Branch GIT ID: [7500a1d19d00706e027f3a924643af94b4caa2c5](https://github.com/liferay/liferay-portal/commit/7500a1d19d00706e027f3a924643af94b4caa2c5)
> 
> #### Sender Branch:
> Branch Name: [LPD-33047-2](https://github.com/algobob/liferay-portal/tree/LPD-33047-2)Branch GIT ID: [344857e9ffa9b900ce3b34ba86b5e2b2c1bd46b1](https://github.com/algobob/liferay-portal/commit/344857e9ffa9b900ce3b34ba86b5e2b2c1bd46b1)
> 
> 0 out of 1jobs PASSED
> #### 1 Failed Jobs:
> * [test-portal-source-format](https://test-1-39.liferay.com/job/test-portal-source-format/7146/)
> 
> ##### For more details click [here](https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/7146/jenkins-report.html).
> format-source-files:
>      [java] java.lang.Exception: Found 1 formatting issues:
>      [java] 1: Do not use org.jsoup, see LPD-42623: ./modules/apps/layout/layout-content-page-editor-web/src/main/java/com/liferay/layout/content/page/editor/web/internal/display/context/ContentPageEditorDisplayContext.java (SourceCheck:IllegalImportsCheck)
>      [java] 
>      [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:472)
>      [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:301)
> [stopwatch] [run.batch.test.action: 1:54.851 sec]
>      [echo] The following error occurred while executing this line:
>      [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
>      [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
>   [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
>   [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
>    [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1389395935.properties
> merge-test-results:
> [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
> [beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
> [junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null820285745
> [junitreport] Loading stylesheet ile:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
> [junitreport] Transform time: 143ms
> [junitreport] Deleting: /tmp/null820285745
> [echo] A report with all the test results can be found at test-results/html/index.html.
> [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
> [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
> [echo] run.batch.test.tear.down.start.timestamp: 12-11-2024 09:03:36:073 PST
> [stopwatch] [run.batch.test.tear.down: 0.001 sec]
> [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
> [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
> [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1389395935.properties
> 
> 
> print-gc-logs:
> [echo]

SF failing seems no be related with my changes. Ignoring it...

2024-12-11 17:20 UTC, algobob commented
ci:test:relevant

2024-12-11 17:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/6412/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6412/jenkins-report.html">here</a>.</b></p>

2024-12-11 19:25 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/6412/">test-portal-acceptance-pullrequest(master)#6412</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6412/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-platform-experience/liferay-portal/pull/796">liferay-platform-experience#796</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/89493852">[master] ci:test:relevant - algobob &gt; liferay-platform-experience - PR#796 - 2024-12-11[09:21:14]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>89493852<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/14119/">publish-testray-report#14119</a><br/></div></div>

2024-12-13 15:26 UTC, algobob commented
ci:test:platform-experience

2024-12-13 15:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>platform-experience</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19223/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/19223/jenkins-report.html">here</a>.</b></p>

2024-12-13 16:31 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:platform-experience - 49 out of 54 jobs passed in 1 hour 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/adcc1b627a7d1c3276fe6d7f20ef2a1b8b0bd543">adcc1b627a7d1c3276fe6d7f20ef2a1b8b0bd543</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/adcc1b627a7d1c3276fe6d7f20ef2a1b8b0bd543">adcc1b627a7d1c3276fe6d7f20ef2a1b8b0bd543</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/91181864">EE Development Acceptance (master) - 1078 - 2024-12-13[04:36:07]</a></p><details><summary><strong>ci:test:platform-experience - 49 out of 54 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19223/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1079123/">functional-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/974803/">functional-tomcat90-mysql57/0/1</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1045866/">functional-tomcat90-mysql57/0/2</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1142878/">functional-tomcat90-mysql57/0/3</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1039169/">functional-tomcat90-mysql57/0/4</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1155332/">functional-tomcat90-mysql57/0/5</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1055387/"><strike>functional-tomcat90-mysql57/0/6</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1104575/"><strike>functional-tomcat90-mysql57/0/7</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995862/">functional-tomcat90-mysql57/0/8</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1038346/">functional-tomcat90-mysql57/0/9</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1155333/"><strike>functional-tomcat90-mysql57/0/10</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995863/">functional-tomcat90-mysql57/0/11</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1055389/">functional-tomcat90-mysql57/0/12</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1055388/">functional-tomcat90-mysql57/0/13</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1248833/">functional-tomcat90-mysql57/0/14</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153730/">functional-tomcat90-mysql57/0/15</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1104576/">functional-tomcat90-mysql57/0/16</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/804156/">functional-tomcat90-mysql57/0/17</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1275383/">functional-tomcat90-mysql57/0/18</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/988141/">functional-tomcat90-mysql57/0/19</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1045865/">functional-tomcat90-mysql57/0/20</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1275382/">functional-tomcat90-mysql57/0/21</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1039168/">functional-tomcat90-mysql57/0/22</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/804155/">functional-tomcat90-mysql57/0/23</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/974802/">functional-tomcat90-mysql57/0/24</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/804154/">functional-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153729/">functional-tomcat90-mysql57/1/1</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1248832/">functional-tomcat90-mysql57/1/2</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/974801/">functional-tomcat90-mysql57/1/3</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/804153/">functional-tomcat90-mysql57/1/4</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1045864/">functional-tomcat90-mysql57/1/5</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1045863/">functional-tomcat90-mysql57/1/6</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995860/">functional-tomcat90-mysql57/1/7</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1104574/">functional-tomcat90-mysql57/1/8</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995861/">functional-tomcat90-mysql57/1/9</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1155331/">functional-tomcat90-mysql57/1/10</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1055390/">functional-tomcat90-mysql57/1/11</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/974804/">functional-tomcat90-mysql57/1/12</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1045862/">functional-tomcat90-mysql57/1/13</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/804157/">functional-tomcat90-mysql57/1/14</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1142879/">functional-tomcat90-mysql57/1/15</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1275384/">functional-tomcat90-mysql57/1/16</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1248834/">functional-tomcat90-mysql57/1/17</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153731/">functional-tomcat90-mysql57/1/18</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/731206/">functional-tomcat90-mysql57/1/19</a></li></ul></li><l [...]

2024-12-13 16:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19223/">test-portal-acceptance-pullrequest(master)#19223</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/19223/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>platform-experience<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-platform-experience/liferay-portal/pull/796">liferay-platform-experience#796</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/91346906">[master] ci:test:platform-experience - algobob &gt; liferay-platform-experience - PR#796 - 2024-12-13[07:26:38]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>91346906<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/41541/">publish-testray-report#41541</a><br/></div></div>

2024-12-13 20:07 UTC, algobob commented
> ### ❌ ci:test:platform-experience - 49 out of 54 jobs passed in 1 hour 5 minutes
> Click here for more details.
> ##### Test bundle downloads:
> * [liferay-portal-bundle-tomcat.tar.gz](https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/19223/bundles/liferay-portal-bundle-tomcat.tar.gz)

It will be fixed in a different PR . Ignoring it for now...

2024-12-13 20:07 UTC, closed without merging