LPD-42390 add functional test and sample
liferay-platform-experience/liferay-portal pull request #806
Opened 2024-11-22 15:37 UTC by thiago-buarqque

Split from https://github.com/liferay-platform-experience/liferay-portal/pull/770

2024-11-22 15:37 UTC, liferay-continuous-integration commented
The following guidelines have been set by the owner of this repository: 
- &nbsp;&nbsp;&nbsp;&nbsp;"Thank you for sending this PR to liferay-platform-experience. If you haven't already,take this opportunity to review our [pull request guidelines](https://liferay.atlassian.net/wiki/spaces/PEDS/pages/2915598365). For additional help,please reach out via the [appropriate channels](https://liferay.atlassian.net/wiki/spaces/PEDS/overview#%3Aslack%3A-Slack-Channels)."

2024-11-27 17:32 UTC, algobob commented
Question: Would be valuable to rename from `liferay-sample-theme-css-4` to `liferay-sample-control-panel-theme-css`?

2024-11-28 09:30 UTC, ethib137 commented
> Question: Would be valuable to rename from `liferay-sample-theme-css-4` to `liferay-sample-control-panel-theme-css`?

This would break the current naming scheme BChan has defined. It's still just a themeCSS client extension so the name needs to be the same.

2024-12-04 17:24 UTC, thiago-buarqque commented
Guys, this one is ready for review @algobob @ethib137

2024-12-04 18:37 UTC, algobob requested changes
Just added one comment :slightly_smiling_face:

2024-12-04 21:22 UTC, thiago-buarqque commented on workspaces/liferay-sample-workspace/client-extensions/liferay-sample-theme-css-4/client-extension.yaml
> +      into: static/images
@algobob  Ops, it shouldn't be two assembles. Just fixed it, thanks

2024-12-04 21:53 UTC, algobob requested changes

2024-12-04 21:53 UTC, algobob commented on workspaces/liferay-sample-workspace/client-extensions/liferay-sample-theme-css-4/client-extension.yaml
> +      into: static/images
Are `img` and `images` two different folders? Maybe we could rename them :thinking:  since these words have same meaning

2024-12-04 22:01 UTC, algobob commented on workspaces/liferay-sample-workspace/client-extensions/liferay-sample-theme-css-4/client-extension.yaml
> +      into: static/images
cool :+1:

2024-12-04 22:02 UTC, algobob approved these changes
LGTM :rocket:

2024-12-05 11:04 UTC, thiago-buarqque commented
ci:test:sf

2024-12-05 11:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/7410/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/7410/jenkins-report.html">here</a>.</b></p>

2024-12-05 11:10 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/103d781e63db4b84fb8e0e26040bceff618a7d5f">103d781e63db4b84fb8e0e26040bceff618a7d5f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thiago-buarqque/liferay-portal/tree/LPD-42390">LPD-42390</a><br/>Branch GIT ID: <a href="https://github.com/thiago-buarqque/liferay-portal/commit/b19b55578ae91236e3ea04462cc29cb3177c6e39">b19b55578ae91236e3ea04462cc29cb3177c6e39</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/7410/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/7410/jenkins-report.html">here</a>.</h5></details></html>

2024-12-05 11:12 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/7410/">test-portal-source-format#7410</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/7410/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-platform-experience/liferay-portal/pull/806">liferay-platform-experience#806</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/84384279">[master] ci:test:sf - thiago-buarqque &gt; liferay-platform-experience - PR#806 - 2024-12-05[03:04:49]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>84384279<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/5360/">publish-testray-report#5360</a><br/></div></div>

2024-12-05 11:13 UTC, thiago-buarqque commented
ci:test:relevant

2024-12-05 12:54 UTC, thiago-buarqque commented
ci:test:relevant

2024-12-05 14:29 UTC, thiago-buarqque commented
ci:test:relevant

2024-12-05 14:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19028/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/19028/jenkins-report.html">here</a>.</b></p>

2024-12-05 16:05 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 23 out of 24 jobs passed</h3><h3>:x: ci:test:relevant - 26 out of 28 jobs passed in 1 hour 35 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/103d781e63db4b84fb8e0e26040bceff618a7d5f">103d781e63db4b84fb8e0e26040bceff618a7d5f</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/103d781e63db4b84fb8e0e26040bceff618a7d5f">103d781e63db4b84fb8e0e26040bceff618a7d5f</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/83965458">EE Development Acceptance (master) - 1060 - 2024-12-04[13:49:02]</a></p><details><summary><strong>ci:test:stable - 23 out of 24 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>central-requirements<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/467556/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448027/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1099220/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1148315/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/443232/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/387631/">js-unit/0/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448023/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/797983/">modules-compile/0/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/726921/">modules-compile/0/1</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/969370/">modules-compile/0/2</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/467562/">modules-compile/0/3</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1099219/">modules-compile/0/4</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1074394/">modules-compile/0/5</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/443231/"><strike>modules-compile/0/6</strike></a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/396939/">modules-compile/0/7</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/797982/">modules-compile/0/8</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1040024/">modules-compile/0/9</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/396940/">modules-compile/0/10</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1074395/">modules-compile/0/11</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1033933/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1244319/">modules-integration-mysql57_stable/0/0</a></li></ul></li><li>modules-unit_stable<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/384113/">modules-unit_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57_stable<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/969369/">playwright-js-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>unit_stable<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/384114/">unit_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>23 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 26 out of 28 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19028/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/467556/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448027/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1099220/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1148315/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/443232/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/387631/">js-unit/0/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448023/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/797983/">modules-compile/0/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/726921/">modules-compile/0/1</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/969370/">modules-compile/0/2</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/467562/">modules-compile/0/3</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1099219/">modules-compile/0/4</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1074394/">modules-compile/0/5</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/443231/"><strike>modules-compile/0/6</strike></a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/396939/">modules-compile/0/7</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/797982/">modules-compile/0/8</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1040024/">modules-compile/0/9</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/396940/">modules-compile/0/10</a></li [...]

2024-12-05 18:03 UTC, thiago-buarqque commented
@ethib137 @algobob CI is broken this week. I ran the test I added **25 times** in a row locally. I see no errors/flakyness. I am sending this to Brian (not sending to BPM since there isn't backend code)

2024-12-05 18:05 UTC, thiago-buarqque commented
Sent to https://github.com/brianchandotcom/liferay-portal/pull/156699

2024-12-05 18:06 UTC, closed without merging